- name: Install full python3
  ansible.builtin.apt:
    pkg: python3-full
  become: true

- name: Install pip3
  ansible.builtin.apt:
    pkg: python3-pip
  become: true

- name: Install python setuptools
  ansible.builtin.apt:
    pkg: python3-setuptools
  become: true

- name: Install python development headers
  ansible.builtin.apt:
    pkg: python3-dev
  become: true

- name: Install build-essential for compiling Python extensions
  ansible.builtin.apt:
    pkg: build-essential
  become: true

- name: Update ~/.profile
  ansible.builtin.blockinfile:
    create: true
    path: ~/.profile
    marker: "# {mark} PYTHON ANSIBLE MANAGED BLOCK"
    mode: "0755"
    block: |
      export PATH=$PATH:$HOME/.local/bin
